# Generated by Django 3.1.2 on 2020-11-17 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Amir', max_length=48),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98b4496b-0db4-47ce-a78d-a195468a24c6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
