# Generated by Django 3.1.2 on 2020-11-17 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20201117_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e4183ca-aada-46d4-b911-876f1c9c4986'), editable=False, primary_key=True, serialize=False),
        ),
    ]
