# Generated by Django 3.1.2 on 2020-12-09 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_auto_20201209_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreserve',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 12, 43, 0, 592867)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
