# Generated by Django 3.1.2 on 2020-12-09 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20201209_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreserve',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 12, 44, 4, 305114)),
        ),
    ]
