# Generated by Django 3.1.2 on 2020-12-09 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_auto_20201209_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodreserve',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 12, 45, 29, 812222)),
        ),
    ]
