# Generated by Django 3.1.2 on 2020-12-09 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_auto_20201209_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreserve',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 14, 45, 56, 554588)),
        ),
    ]
