# Generated by Django 3.1.2 on 2020-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_auto_20201209_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreserve',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
