# Generated by Django 3.1.2 on 2020-12-09 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_auto_20201209_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreserve',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 9)),
        ),
    ]
