# Generated by Django 3.1.2 on 2021-01-16 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_auto_20201209_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreserve',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 16)),
        ),
    ]
