# Generated by Django 3.1.2 on 2021-01-25 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_auto_20210116_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.CharField(choices=[('b', 'breakfast'), ('l', 'launch'), ('d', 'dinner')], default='launch', max_length=16),
        ),
        migrations.AlterField(
            model_name='foodreserve',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 25)),
        ),
    ]
